### ISSUE TITLE
Linemod detection causing std::bad_alloc

### ISSUE THREAD

**Issue by trykks** [wg-perception/linemod#27]
I've been trying to run the linemod detection tutorial found here: http://wg-perception.github.io/ork_tutorials/tutorial03/tutorial.html

Training phase works fine, but the detection phase throws the following error:

**-----------------------------------------------------------------------------------------------------------**

[ INFO] [1434356493.822010980]: Initialized ROS. node_name: /object_recognition_server 
[ INFO] [1434356494.100826452]: System already initialized. node_name: /object_recognition_server 
[ INFO] [1434356494.108034166]: Subscribed to topic:/camera/depth_registered/camera_info with queue size of 1 
[ INFO] [1434356494.111847947]: Subscribed to topic:/camera/rgb/camera_info with queue size of 1 
[ INFO] [1434356494.118495788]: Subscribed to topic:/camera/rgb/image_rect_color with queue size of 1 
[ INFO] [1434356494.123829464]: Subscribed to topic:/camera/depth_registered/image_raw with queue size of 1 
Traceback (most recent call last): 
  File "/home/astrostudent/ork/src/object_recognition_core/apps/detection", line 24, in <module> 
    run_plasm(args, plasm) 
  File "/home/astrostudent/ork/src/ecto/python/ecto/opts.py", line 85, in run_plasm 
    sched.execute(options.niter) 
ecto.CellException:            exception_type  CellException 
[cell_name] = pipeline1 

[function_name] = process_with_only_these_inputs 

[type] = std::bad_alloc 

[what] = std::bad_alloc 

[when] = While triggering param change callbacks

**-----------------------------------------------------------------------------------------------------------**

Any ideas on how to fix this?

**Comment by xMutzelx** [comment]
How did you fix your problem? A short explanation would be nice.

**Comment by trykks** [comment]
I'm afraid I didn't.

I'm just really new to GitHub and found the same issues discussed in another thread (a still open issue) and thought the best way was to close it.
I'm unaware of the meaning of closing an issue so I'll reopen it!
Sorry!

**Comment by xMutzelx** [comment]
No problem, you can also post a link to the other thread. Thank you for your help.
